# Generated by Django 4.0.4 on 2022-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=9)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('national', models.CharField(choices=[('Yemeni', 'Yemeni'), ('Saudi', 'Saudi')], default='Yemeni', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disactive', 'Disactive')], max_length=20)),
            ],
        ),
    ]
