# Generated by Django 4.0.4 on 2022-06-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_mark',
            field=models.ManyToManyField(blank=True, to='certificate.student_subject'),
        ),
    ]
