# Generated by Django 4.0.4 on 2022-06-05 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('الأول', 'الأول'), ('الثاني', 'الثاني')], default='الأول', max_length=20)),
                ('level', models.CharField(choices=[('الأول', 'الأول'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='الأول', max_length=20)),
                ('year', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='collage',
            name='dean',
        ),
        migrations.RemoveField(
            model_name='student_subject',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='student_subject',
            name='first_year',
        ),
        migrations.RemoveField(
            model_name='student_subject',
            name='level',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='national',
            field=models.CharField(choices=[('يمني', 'يمني'), ('سعودي', 'سعودي')], default='Yemeni', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('مقيد', 'مقيد'), ('Disactive', 'Disactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='certificate.term'),
        ),
    ]
