# Generated by Django 4.0.4 on 2022-06-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_term_remove_collage_dean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_subject',
            name='note',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
