# Generated by Django 4.0.4 on 2022-06-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='part',
        ),
        migrations.RemoveField(
            model_name='part',
            name='collage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student_subject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student_subject',
            name='term',
        ),
        migrations.DeleteModel(
            name='Collage',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Student_subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
