# Generated by Django 4.0.4 on 2022-06-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0014_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
