# Generated by Django 4.0.4 on 2022-06-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0015_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
    ]
