# Generated by Django 4.0.4 on 2022-06-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0016_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='note',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
