# Generated by Django 4.0.4 on 2022-06-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0017_student_certificate_alter_student_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_stamp', models.ImageField(blank=True, null=True, upload_to='')),
                ('register_stamp', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
