# Generated by Django 4.0.4 on 2022-06-13 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0018_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_subject',
            name='subject',
            field=models.ForeignKey(limit_choices_to={'pk': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='certificate.subject'),
        ),
    ]
