# Generated by Django 4.0.4 on 2022-06-13 11:13

import certificate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate', '0020_remove_major_part_remove_part_collage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', max_length=9)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('national', models.CharField(choices=[('يمني', 'يمني'), ('سعودي', 'سعودي')], default='يمني', max_length=20)),
                ('status', models.CharField(choices=[('مقيد', 'مقيد'), ('Disactive', 'Disactive')], default='Active', max_length=20)),
                ('start_date', models.CharField(default=0, max_length=50)),
                ('current_level', models.CharField(choices=[('الأول', 'الأول'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='First', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='certificate.major')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('الأول', 'الأول'), ('الثاني', 'الثاني')], default='الأول', max_length=20)),
                ('level', models.CharField(choices=[('الأول', 'الأول'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='الأول', max_length=20)),
                ('year', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_stamp', models.ImageField(blank=True, null=True, upload_to='')),
                ('register_stamp', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم')),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='certificate.collage')),
            ],
        ),
        migrations.CreateModel(
            name='Student_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(default=0.0)),
                ('note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='certificate.student')),
                ('subject', models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='certificate.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='certificate.term')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage', to='certificate.collage')),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='certificate.part'),
        ),
    ]
