# Generated by Django 4.0.4 on 2022-06-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0021_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='collage',
        ),
    ]
