# Generated by Django 4.0.4 on 2022-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0022_remove_subject_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_level',
            field=models.CharField(choices=[('الأول', 'الأول'), ('الثاني', 'الثاني'), ('الثالث', 'الثالث'), ('الرابع', 'الرابع')], default='First', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('مقيد', 'مقيد'), ('تخرج', 'متخرج')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_subject',
            name='note',
            field=models.CharField(blank=True, default='....', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='level',
            field=models.CharField(choices=[('الأول', 'الأول'), ('الثاني', 'الثاني'), ('الثالث', 'الثالث'), ('الرابع', 'الرابع')], default='الأول', max_length=20),
        ),
    ]
